"""New Migration

Revision ID: 09ed2f529061
Revises: b9fc07e21496
Create Date: 2022-04-14 22:46:16.931901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ed2f529061'
down_revision = 'b9fc07e21496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
