"""New Migration

Revision ID: 19a6725166a3
Revises: d0cbc59624ae
Create Date: 2022-04-14 22:36:38.557106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a6725166a3'
down_revision = 'd0cbc59624ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
