"""New Migration

Revision ID: 4b72afa8ca81
Revises: 723ac2848f8b
Create Date: 2022-04-14 22:14:04.207169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b72afa8ca81'
down_revision = '723ac2848f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
