"""New Migration

Revision ID: 6b7253bbe54d
Revises: 4b72afa8ca81
Create Date: 2022-04-14 22:16:53.016403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7253bbe54d'
down_revision = '4b72afa8ca81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
