"""New Migration

Revision ID: 723ac2848f8b
Revises: 7df8e181ba20
Create Date: 2022-04-14 21:48:33.514902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723ac2848f8b'
down_revision = '7df8e181ba20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
