"""New Migration

Revision ID: 94f1444bbf30
Revises: a31b04fa6492
Create Date: 2022-04-15 00:14:04.426970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f1444bbf30'
down_revision = 'a31b04fa6492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
