"""New Migration

Revision ID: 9dfb648e3ce4
Revises: 09ed2f529061
Create Date: 2022-04-14 22:50:27.000708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dfb648e3ce4'
down_revision = '09ed2f529061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
