"""New Migration

Revision ID: a31b04fa6492
Revises: aa63ef44f6cb
Create Date: 2022-04-14 23:17:27.147784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31b04fa6492'
down_revision = 'aa63ef44f6cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
