"""New Migration

Revision ID: aa63ef44f6cb
Revises: 9dfb648e3ce4
Create Date: 2022-04-14 22:52:21.844016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa63ef44f6cb'
down_revision = '9dfb648e3ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
