"""New Migration

Revision ID: b9fc07e21496
Revises: 19a6725166a3
Create Date: 2022-04-14 22:40:19.552454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9fc07e21496'
down_revision = '19a6725166a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
