"""New Migration

Revision ID: d0cbc59624ae
Revises: 6b7253bbe54d
Create Date: 2022-04-14 22:26:34.523352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0cbc59624ae'
down_revision = '6b7253bbe54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
